version: '3.4'

services:
  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
#  identityserver:
#    image: ${DOCKER_REGISTRY-}identityserver
#    build:
#      context: .
#      dockerfile: Infrastructure/EShopping.Identity/Dockerfile
      
volumes: 
  elasticsearch-data:   
  mongo_data: